version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4      # any official tag works
    platform: linux/amd64              # ← forces x86 layer, QEMU handles it
    environment:
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
      POSTGRES_DB: gis
    ports: ["5432:5432"]

  pgadmin:
    image: dpage/pgadmin4:8
    platform: linux/arm64/v8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

  valhalla-build:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest        # ← public multi‑arch
    platform: linux/arm64/v8
    entrypoint: ["sleep","infinity"]
volumes:
  pgdata:
